### ISSUE TITLE
Exhaust valve needed

### ISSUE THREAD

**Issue by Cyrko** [strangeparts/gasmask#5]
[edit] It seems this issue has been expressed while I wrote this one. Sorry for the duplicate

Hi ! 

Thanks for your project ! It seems very promising however I think there needs to be an exhaust port on the mask. Since it is difficult to breathe through the filter, it would be greatly beneficial to expire effortlessly. It would also help to manage the humidity in the filter. I am speculating but I guess that a damp one would be less effective since the activated charcoal would be clogged up.

Here are some reference picture from a mask I used during my military service: 

![IMG_20200615_222554](https://user-images.githubusercontent.com/15278386/84706874-08581b80-af5e-11ea-817b-3ecfed12f456.jpg)
Behind the "grate" is a voice diaphragm. The two lower oppenings are the inlets and outlets. Each one of them houses a one way valve. 

![IMG_20200615_221536](https://user-images.githubusercontent.com/15278386/84706631-9c75b300-af5d-11ea-969d-01dd801cfd44.jpg)
This is a close-up of the outlet

![IMG_20200615_222434](https://user-images.githubusercontent.com/15278386/84706738-c929ca80-af5d-11ea-9bc6-596326752a28.jpg)
The gray opening is just the voice diaphragm.
![IMG_20200615_222406](https://user-images.githubusercontent.com/15278386/84706748-ce871500-af5d-11ea-9aa6-56b6d876591f.jpg)
![IMG_20200615_221950](https://user-images.githubusercontent.com/15278386/84706757-d2b33280-af5d-11ea-8bfd-21bbebf1967c.jpg)
![IMG_20200615_222728](https://user-images.githubusercontent.com/15278386/84707124-6c7adf80-af5e-11ea-8614-ebaa5fa51c03.jpg)
![IMG_20200615_222758](https://user-images.githubusercontent.com/15278386/84707128-6f75d000-af5e-11ea-9dfe-348028b774ce.jpg)
The rubber of the valve is pretty thin so it may be possible to use balloons to make membranes. Their curved shape may be used to ensure a tight contact and mimic the bevel of the original one. 
![Baloon](https://user-images.githubusercontent.com/15278386/84708474-e3b17300-af60-11ea-878f-03c35f40f679.jpg)

Regarding the nose and mouth separate area, it appears that its primary function is to unfog the lenses using fresh air. Since the eyes are extremely sensitive it makes sense to have only one effective seal around the mask. 
![IMG_20200615_223434](https://user-images.githubusercontent.com/15278386/84705707-1dcc4600-af5c-11ea-9de5-6cd29993f41c.jpg)
![IMG_20200615_223507](https://user-images.githubusercontent.com/15278386/84705722-2290fa00-af5c-11ea-8e76-9e3f36d8f256.jpg)
![IMG_20200615_223600](https://user-images.githubusercontent.com/15278386/84705744-27ee4480-af5c-11ea-9d0e-9885202a8e27.jpg)
![IMG_20200615_221928](https://user-images.githubusercontent.com/15278386/84709463-79013700-af62-11ea-9047-6f189457dfbd.jpg)

Thanks again for your work and I hope to be able to help you further !

**Comment by 3devangelist** [comment]
I have made one for covid, to test out materials and use TPU, 
https://wikifactory.com/+movimentomakerpt/diy-paper-mask

**Comment by stephen304** [comment]
I made a lengthy comment on the previous issue about vent ports and some of the stuff we've been discussing in the discord channel. But I'll add a few comments based on what you've suggested:

* What are your thoughts on the importance of valves on both the filter and outlet? I think so far we've been discussing having just an exhale valve to prevent air intake when breathing in. When exhaling, the pressure difference should be relatively low if the vent port is working, but some humid air may go back through the filter. I'm not too knowledgeable about this
* For your balloon idea, would you like to design or spec out a valve based on this idea? We have a couple valve ideas in development, and plan on making them threaded so assemblers can choose a valve based on requirements and materials they have available. So if you could assist with a prototype using a balloon, we could add it to the options
* I'm not sure I completely understand the last part about airflow between the 2 sections of the mask - is the design of your mask so that air intake comes into the eye area and leaves from the mouth area? And is there a vent hole to allow free flow of air between the 2 chambers or do you think another one way valve would help to control the flow of humid air from exhaling reaching the eye area?

**Comment by justinl681** [comment]
Hello! The design team and I are working on a one-way valve. If you'd like, check my pinned github page and give feedback!

**Comment by stephen304** [comment]
There are now a couple of valve designs, one of which is tested, so I would suggest closing this issue and creating new ones for any remaining concerns
